# -*- coding: utf-8 -*-
"""data-validating.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DahTYfn7U7VlyhUlDQzst2eCblDs5GK-
"""

import pandas as pd
import os
from google.colab import files
from datetime import datetime
from collections import defaultdict
import matplotlib.pyplot as plt
import csv
import numpy as np
from scipy.stats import shapiro
file_name = 'employees.csv'

# Get the file size in bytes
file_size_bytes = os.path.getsize(file_name)

# Count the number of rows
with open(file_name, 'r') as f:
    row_count = sum(1 for line in f)
row_count = row_count - 1 #(excluding header)
print(f"File size: {file_size_bytes} bytes")
print(f"Number of records (excluding header): {row_count}")


#2 slide
invalid_rows = 0

# Open the CSV file and check each row
with open(file_name, 'r') as csvfile:
    csv_reader = csv.DictReader(csvfile)

    # Loop through each row in the CSV
    for row_number, row in enumerate(csv_reader, start=2):  # start=2 because row 1 is header
        # Check if the "name" field exists and is not empty
        if "name" not in row or not row["name"].strip():
            invalid_rows += 1

print(f"Total rows with missing or empty 'name' field: {invalid_rows}")

# NEW ASSERTION = Every record must include a non-empty "employee_id".
invalid_rows = 0

# Open the CSV file and check each row
with open(file_name, 'r') as csvfile:
    csv_reader = csv.DictReader(csvfile)

    # Loop through each row in the CSV
    for row_number, row in enumerate(csv_reader, start=2):  # start=2 because row 1 is header
        if "name" not in row or not row["eid"].strip():
            invalid_rows += 1
print(f"Total rows with missing or empty 'employee id' field: {invalid_rows}")


#slide 3

invalid_hire_date_rows = 0

with open(file_name, 'r') as csvfile:
    csv_reader = csv.DictReader(csvfile)

    for row in csv_reader:
        hire_date_str = row["hire_date"].strip()
        hire_date = datetime.strptime(hire_date_str, '%Y-%m-%d')

        if hire_date.year < 2015:
            invalid_hire_date_rows += 1

print(f"Total employees hired before 2015: {invalid_hire_date_rows}")

#MY assertion
invalid_salary_rows = 0

with open(file_name, 'r') as csvfile:
    csv_reader = csv.DictReader(csvfile)

    for row in csv_reader:
        try:
            salary = float(row["salary"].strip())  # Convert the salary field to float
            if salary < 90000:
                invalid_salary_rows += 1
        except ValueError:
            # If salary is not a valid number, count it as invalid
            invalid_salary_rows += 1

print(f"Total employees with salary below $90,000: {invalid_salary_rows}")

########################################
#slide 4
invalid_birth_before_hire_rows = 0

with open(file_name, 'r') as csvfile:
    csv_reader = csv.DictReader(csvfile)

    for row in csv_reader:
        # Parse birth_date and hire_date
        birth_date_str = row["birth_date"].strip()
        hire_date_str = row["hire_date"].strip()

        # Convert the date strings to datetime objects
        birth_date = datetime.strptime(birth_date_str, '%Y-%m-%d')
        hire_date = datetime.strptime(hire_date_str, '%Y-%m-%d')

        # Check if birth_date is after or equal to hire_date
        if birth_date >= hire_date:
            invalid_birth_before_hire_rows += 1

# Print the result
print(f"Total records where birth date is after hire date: {invalid_birth_before_hire_rows}")


###################################################################

#slide 5
invalid_manager_records = 0

# Create a set to hold all valid employee IDs (eid)
valid_eids = set()

# Step 1: Read the file and collect valid employee IDs
with open(file_name, 'r') as csvfile:
    csv_reader = csv.DictReader(csvfile)

    # First pass: collect all employee IDs (eid)
    for row in csv_reader:
        eid = row["eid"].strip()  # Get the employee ID (eid)
        valid_eids.add(eid)  # Add it to the set of valid employee IDs

# Step 2: read the file to validate the reports_to column
with open(file_name, 'r') as csvfile:
    csv_reader = csv.DictReader(csvfile)

    # Second pass: check if the manager (reports_to) exists in the set of valid eids
    for row in csv_reader:
        manager_eid = row["reports_to"].strip()  # Get the manager's employee ID

        # Check if the manager's eid is valid (exists in the valid_eids set)
        if manager_eid not in valid_eids:
            invalid_manager_records += 1  # Increment counter if invalid
print(f"Total records where the manager does not exist as an employee: {invalid_manager_records}")

#####################################################################################


# Initialize a counter to track invalid records where employee title is the same as manager title
invalid_title_records = 0

# Step 1: Read the file and collect title information
# We'll create a dictionary to map each employee's `eid` to their `title`
employee_titles = {}

# First pass: Collect employee `eid` and `title`
with open(file_name, 'r') as csvfile:
    csv_reader = csv.DictReader(csvfile)

    for row in csv_reader:
        eid = row["eid"].strip()  # Employee ID (eid)
        title = row["title"].strip()  # Employee title
        employee_titles[eid] = title  # Store the employee's title in the dictionary

# Step 2: Check if employee title matches manager title
with open(file_name, 'r') as csvfile:
    csv_reader = csv.DictReader(csvfile)

    for row in csv_reader:
        eid = row["eid"].strip()  # Employee ID (eid)
        title = row["title"].strip()  # Employee title
        manager_eid = row["reports_to"].strip()  # Manager's employee ID (reports_to)

        # If the employee has a manager and the manager's title matches the employee's title
        if manager_eid in employee_titles:
            manager_title = employee_titles[manager_eid]  # Get the manager's title

            if title == manager_title:
                invalid_title_records += 1  # Increment counter if titles are the same

# Step 3: Print the result
print(f"Total records where employee title matches manager title: {invalid_title_records}")



################################################################################
#Summary Assertion
city_employee_count = defaultdict(int)

# Step 1: Read the file and count employees per city
with open(file_name, 'r') as csvfile:
    csv_reader = csv.DictReader(csvfile)

    for row in csv_reader:
        city = row["city"].strip()  # Get the city for each employee
        city_employee_count[city] += 1  # Increment the count for the city

# Step 2: Check for cities with fewer than two employees
cities_with_one_employee = 0

# Loop through the dictionary to find cities with exactly one employee
for city, count in city_employee_count.items():
    if count < 2:
        cities_with_one_employee += 1  # Increment if the city has fewer than 2 employees

# Step 3: Print the result
if cities_with_one_employee > 0:
    print(f"Dataset is not valid. {cities_with_one_employee} city(ies) have only one employee.")
else:
    print("Dataset is valid. Each city has more than one employee.")
##############################################################################


# Initialize a set to track employee ids and a counter for duplicates
employee_ids = set()
duplicate_eids = 0

# Step 1: Read the file and check for duplicate employee ids
with open(file_name, 'r') as csvfile:
    csv_reader = csv.DictReader(csvfile)

    for row in csv_reader:
        eid = row["eid"].strip()  # Get the employee ID (eid)

        # If the eid is already in the set then it's a duplicate
        if eid in employee_ids:
            duplicate_eids += 1  # Increment the counter for duplicate eids
        else:
            employee_ids.add(eid)  # Add the eid to the set if it's not a duplicate

# Step 2: Print the result
if duplicate_eids > 0:
    print(f"Dataset is not valid. {duplicate_eids} duplicate employee id(s) found.")
else:
    print("Dataset is valid. Each employee has a unique employee id.")


####################################################################
#slide 7
# Initialize a list to store the salaries
salaries = []

# Step 1: Read the CSV file and collect salaries
with open(file_name, 'r') as csvfile:
    csv_reader = csv.DictReader(csvfile)

    for row in csv_reader:
        salary = row["salary"].strip()  # Get the salary for each employee
        try:
            salary = float(salary)  # Convert the salary to a float
            salaries.append(salary)  # Add the salary to the list
        except ValueError:
            continue  # Skip any rows with invalid salary values

# Step 2: Plot the histogram of salaries
plt.figure(figsize=(10, 6))
plt.hist(salaries, bins=30, color='skyblue', edgecolor='black')
plt.title('Histogram of Employee Salaries')
plt.xlabel('Salary')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

# Step 3:normality test (Shapiro-Wilk test)
stat, p_value = shapiro(salaries)

# Step 4: Interpret the result
print(f"Shapiro-Wilk Test Statistic: {stat}")
print(f"P-value: {p_value}")
if p_value > 0.05:
    print("The salaries are likely normally distributed (fail to reject H0).")
else:
    print("The salaries are not normally distributed (reject H0).")


#######################################################################