# -*- coding: utf-8 -*-
"""data_bias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMM8cGjXdUjQGzdnQmSLehGSQAygeT2i
"""

import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime, timedelta
from io import StringIO
from scipy.stats import binomtest, ttest_1samp, chi2_contingency

# Step 1: Correctly parse HTML with multiple trip sections
print("Loading and parsing HTML file...")
with open("trimet_stopevents_2022-12-07.html", "r", encoding="utf-8") as f:
    raw_html = f.read()

soup = BeautifulSoup(raw_html, "html.parser")

# Find all headings for each trip (this was the key missing piece)
headings = soup.find_all("h2", string=lambda t: t and t.strip().startswith("Stop events for PDX_TRIP"))

frames = []
base_date = datetime.strptime("2022-12-07", "%Y-%m-%d")

print(f"Found {len(headings)} trip sections...")

for hdr in headings:
    text = hdr.get_text(strip=True)
    parts = text.split()
    trip = parts[-1]  # Extract trip ID

    # Find the table after this heading
    tbl = hdr.find_next_sibling("table")
    if tbl is None:
        tbl = hdr.find_next("table")
    if tbl is None:
        print(f"Warning: no table found after heading '{text}'")
        continue

    # Parse the table
    df_temp = pd.read_html(StringIO(str(tbl)))[0]

    # Handle missing values in arrive_time
    df_temp = df_temp.dropna(subset=['arrive_time'])  # Remove rows with missing arrive_time
    df_temp["tstamp"] = df_temp["arrive_time"].apply(
        lambda s: base_date + timedelta(seconds=int(s)) if pd.notna(s) else None
    )

    # Select relevant columns and add trip_id
    # Make sure we have all required columns
    required_cols = ["vehicle_number", "tstamp", "location_id", "ons", "offs"]
    if all(col in df_temp.columns for col in required_cols):
        sub_df = df_temp[required_cols].copy()
        sub_df.insert(0, "trip_id", trip)
        frames.append(sub_df)
    else:
        print(f"Warning: Missing required columns in trip {trip}, skipping...")

# Combine all trips
if frames:
    stops_df = pd.concat(frames, ignore_index=True)
    # Remove any remaining rows with missing timestamps
    stops_df = stops_df.dropna(subset=['tstamp'])
else:
    print("Error: No valid trip data found!")
    exit()

print(f"Loaded {len(stops_df):,} stop events")
expected_count = 93912
if len(stops_df) == expected_count:
    print("✓ Loaded expected 93,912 records")
else:
    print(f"⚠ Expected {expected_count:,} but got {len(stops_df):,}")
    print("  This may be due to data cleaning or missing values")

# Step 2: Basic Analysis (from your original code)
print("\n" + "="*50)
print("BASIC ANALYSIS")
print("="*50)

num_vehicles = stops_df['vehicle_number'].nunique()
print(f"A. Number of vehicles: {num_vehicles:,}")

num_locations = stops_df['location_id'].nunique()
print(f"B. Number of unique stop locations: {num_locations:,}")

min_tstamp = stops_df['tstamp'].min()
max_tstamp = stops_df['tstamp'].max()
print(f"C. Time range: {min_tstamp} to {max_tstamp}")

num_boardings = (stops_df['ons'] >= 1).sum()
print(f"D. Stop events with at least one boarding: {num_boardings:,}")

percent_boardings = (num_boardings / len(stops_df)) * 100
print(f"E. Percentage of such stop events: {percent_boardings:.2f}%")

# Step 3: Validate specific cases
print("\n" + "="*50)
print("VALIDATION - SPECIFIC CASES")
print("="*50)

# Location 6913 analysis
loc_df = stops_df[stops_df['location_id'] == 6913]
num_stops_loc = len(loc_df)
unique_buses_loc = loc_df['vehicle_number'].nunique()
pct_with_boarding_loc = (loc_df['ons'] >= 1).sum() / num_stops_loc * 100 if num_stops_loc > 0 else 0

print(f"A.i. Number of stops at location 6913: {num_stops_loc:,}")
print(f"A.ii. Unique buses at location 6913: {unique_buses_loc:,}")
print(f"A.iii. % of stops at location 6913 with boarding: {pct_with_boarding_loc:.2f}%")

# Vehicle 4062 analysis
veh_df = stops_df[stops_df['vehicle_number'] == 4062]
num_stops_veh = len(veh_df)
total_ons = veh_df['ons'].sum()
total_offs = veh_df['offs'].sum()
pct_with_boarding_veh = (veh_df['ons'] >= 1).sum() / num_stops_veh * 100 if num_stops_veh > 0 else 0

print(f"B.i. Number of stops by vehicle 4062: {num_stops_veh:,}")
print(f"B.ii. Total passengers boarded on 4062: {total_ons:,}")
print(f"B.iii. Total passengers deboarded from 4062: {total_offs:,}")
print(f"B.iv. % of 4062's stops with at least one boarding: {pct_with_boarding_veh:.2f}%")

# Step 4: Find vehicles with biased boarding data
print("\n" + "="*50)
print("BOARDING BIAS ANALYSIS")
print("="*50)

# Calculate system-wide boarding rate
system_p = (stops_df['ons'] >= 1).mean()
print(f"System-wide proportion of stops with boardings: {system_p:.4f} ({system_p * 100:.2f}%)")

# Test each vehicle for bias
results = []
biased_vehicles = []

print(f"\nTesting {stops_df['vehicle_number'].nunique()} vehicles...")
print("Vehicle | Stops | Boarding_Stops | Rate | p-value | Biased")
print("-" * 65)

for vehicle_id, group in stops_df.groupby('vehicle_number'):
    total_stops = len(group)
    boarding_stops = (group['ons'] >= 1).sum()
    boarding_rate = boarding_stops / total_stops if total_stops > 0 else 0

    # Perform binomial test
    test = binomtest(k=boarding_stops, n=total_stops, p=system_p, alternative='two-sided')
    p_value = test.pvalue

    is_biased = p_value < 0.05
    bias_indicator = "*" if is_biased else ""

    print(f"{vehicle_id:7} | {total_stops:5} | {boarding_stops:14} | {boarding_rate:5.3f} | {p_value:.6f} | {bias_indicator}")

    results.append({
        'vehicle_id': vehicle_id,
        'total_stops': total_stops,
        'boarding_stops': boarding_stops,
        'boarding_rate': boarding_rate,
        'p_value': p_value
    })

    if is_biased:
        biased_vehicles.append({
            'vehicle_id': vehicle_id,
            'p_value': p_value,
            'boarding_rate': boarding_rate
        })

print(f"\nVehicles with biased boarding data (p < 0.05): {len(biased_vehicles)}")
if biased_vehicles:
    print("\nBiased vehicles (sorted by p-value):")
    for vehicle in sorted(biased_vehicles, key=lambda x: x['p_value']):
        direction = "HIGH" if vehicle['boarding_rate'] > system_p else "LOW"
        print(f"  Vehicle {vehicle['vehicle_id']}: p={vehicle['p_value']:.6f}, rate={vehicle['boarding_rate']:.3f} ({direction})")

# Step 5: GPS Bias Analysis (if GPS data is available)
print("\n" + "="*50)
print("GPS BIAS ANALYSIS")
print("="*50)

try:
    gps_df = pd.read_csv("trimet_relpos_2022-12-07.csv")
    print(f"Loaded {len(gps_df):,} GPS records")

    # Standardize column names
    gps_df.columns = [col.upper() for col in gps_df.columns]
    if 'VEHICLE_NUMBER' in gps_df.columns:
        gps_df = gps_df.rename(columns={'VEHICLE_NUMBER': 'vehicle_number'})

    # GPS bias analysis
    relpos_values = gps_df['RELPOS'].dropna()
    overall_mean = relpos_values.mean()
    overall_std = relpos_values.std()

    print(f"Overall RELPOS: mean={overall_mean:.6f}, std={overall_std:.6f}, count={len(relpos_values):,}")

    gps_biased_vehicles = []
    alpha = 0.005  # Stricter threshold for GPS bias

    print(f"\nTesting GPS bias for vehicles (α={alpha}):")
    print("Vehicle | Count | Mean_RELPOS | Std_RELPOS | p-value | Biased")
    print("-" * 70)

    for vehicle_id, group in gps_df.groupby('vehicle_number'):
        vehicle_relpos = group['RELPOS'].dropna()

        if len(vehicle_relpos) < 10:  # Minimum sample size
            continue

        vehicle_mean = vehicle_relpos.mean()
        vehicle_std = vehicle_relpos.std()

        # One-sample t-test against overall mean
        t_stat, p_value = ttest_1samp(vehicle_relpos, overall_mean)

        is_biased = p_value < alpha
        bias_indicator = "*" if is_biased else ""

        print(f"{vehicle_id:7} | {len(vehicle_relpos):5} | {vehicle_mean:11.6f} | {vehicle_std:10.6f} | {p_value:.6f} | {bias_indicator}")

        if is_biased:
            direction = "RIGHT" if vehicle_mean > 0 else "LEFT"
            gps_biased_vehicles.append({
                'vehicle_id': vehicle_id,
                'p_value': p_value,
                'mean_relpos': vehicle_mean,
                'direction': direction
            })

    print(f"\nVehicles with GPS bias (p < {alpha}): {len(gps_biased_vehicles)}")
    if gps_biased_vehicles:
        print("\nGPS-biased vehicles:")
        for vehicle in sorted(gps_biased_vehicles, key=lambda x: x['p_value']):
            print(f"  Vehicle {vehicle['vehicle_id']}: p={vehicle['p_value']:.6f}, "
                  f"mean={vehicle['mean_relpos']:.6f} ({vehicle['direction']} bias)")

except FileNotFoundError:
    print("GPS data file not found - skipping GPS bias analysis")

# Step 6: Offs/Ons Bias Analysis
print("\n" + "="*50)
print("OFFS/ONS BIAS ANALYSIS")
print("="*50)

total_offs = stops_df['offs'].sum()
total_ons = stops_df['ons'].sum()
total_passengers = total_offs + total_ons
system_offs_prop = total_offs / total_passengers if total_passengers > 0 else 0
system_ons_prop = total_ons / total_passengers if total_passengers > 0 else 0

print(f"System totals: offs={total_offs:,}, ons={total_ons:,}")
print(f"System proportions: offs={system_offs_prop:.4f}, ons={system_ons_prop:.4f}")

offs_ons_biased = []
alpha = 0.05

print(f"\nTesting offs/ons bias (χ² test, α={alpha}):")
print("Vehicle | Offs | Ons | Offs% | Ons% | p-value | Biased")
print("-" * 65)

for vehicle_id, group in stops_df.groupby('vehicle_number'):
    vehicle_offs = int(group['offs'].sum())
    vehicle_ons = int(group['ons'].sum())
    vehicle_total = vehicle_offs + vehicle_ons

    if vehicle_total == 0:
        continue

    vehicle_offs_prop = vehicle_offs / vehicle_total
    vehicle_ons_prop = vehicle_ons / vehicle_total

    # Chi-square test
    contingency_table = [
        [vehicle_offs, vehicle_ons],
        [total_offs - vehicle_offs, total_ons - vehicle_ons]
    ]

    chi2, p_value, dof, expected = chi2_contingency(contingency_table)

    # Check if expected frequencies are adequate
    if (expected < 5).any():
        continue

    is_biased = p_value < alpha
    bias_indicator = "*" if is_biased else ""

    print(f"{vehicle_id:7} | {vehicle_offs:4} | {vehicle_ons:3} | {vehicle_offs_prop*100:5.2f}% | "
          f"{vehicle_ons_prop*100:5.2f}% | {p_value:.6f} | {bias_indicator}")

    if is_biased:
        bias_type = "more offs" if vehicle_offs_prop > system_offs_prop else "more ons"
        offs_ons_biased.append({
            'vehicle_id': vehicle_id,
            'p_value': p_value,
            'bias_type': bias_type,
            'offs_prop': vehicle_offs_prop,
            'ons_prop': vehicle_ons_prop
        })

print(f"\nVehicles with offs/ons bias (p < {alpha}): {len(offs_ons_biased)}")
if offs_ons_biased:
    print("\nOffs/Ons biased vehicles:")
    for vehicle in sorted(offs_ons_biased, key=lambda x: x['p_value']):
        print(f"  Vehicle {vehicle['vehicle_id']}: p={vehicle['p_value']:.6f} ({vehicle['bias_type']})")