# -*- coding: utf-8 -*-
"""data_bias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMM8cGjXdUjQGzdnQmSLehGSQAygeT2i
"""

!pip install beautifulsoup4
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime, timedelta
from scipy.stats import binomtest
from scipy.stats import ttest_ind

# Step 1: Open the stop events HTML file
with open("trimet_stopevents_2022-12-07.html", "r") as f:
    soup = BeautifulSoup(f, "html.parser")

# Step 2: Extract the first HTML table
table = soup.find("table")

# Step 3: Convert the table to a DataFrame
df = pd.read_html(str(table))[0]

# Step 4: Preview the data
df.head()

print(df.columns.tolist())

base_date = datetime(2022, 12, 7)  # Based on file name / instructions
df['tstamp'] = df['arrive_time'].apply(lambda x: base_date + timedelta(seconds=int(x)))

stops_df = df[['trip_number', 'vehicle_number', 'tstamp', 'location_id', 'ons', 'offs']].copy()

stops_df.rename(columns={'trip_number': 'trip_id'}, inplace=True)

print("Total stop events:", len(stops_df))
stops_df.head()

num_vehicles = stops_df['vehicle_number'].nunique()
print("A. Number of vehicles:", num_vehicles)

num_locations = stops_df['location_id'].nunique()
print("B. Number of unique stop locations:", num_locations)

min_tstamp = stops_df['tstamp'].min()
max_tstamp = stops_df['tstamp'].max()
print("C. Min tstamp:", min_tstamp)
print("   Max tstamp:", max_tstamp)

num_boardings = (stops_df['ons'] >= 1).sum()
print("D. Stop events with at least one boarding:", num_boardings)

percent_boardings = (num_boardings / len(stops_df)) * 100
print(f"E. Percentage of such stop events: {percent_boardings:.2f}%")

loc_df = stops_df[stops_df['location_id'] == 6913]
num_stops_loc = len(loc_df)

unique_buses_loc = loc_df['vehicle_number'].nunique()

pct_with_boarding_loc = (loc_df['ons'] >= 1).sum() / num_stops_loc * 100 if num_stops_loc > 0 else 0

print("A.i. Number of stops at location 6913:", num_stops_loc)
print("A.ii. Unique buses at location 6913:", unique_buses_loc)
print(f"A.iii. % of stops at location 6913 with boarding: {pct_with_boarding_loc:.2f}%")

veh_df = stops_df[stops_df['vehicle_number'] == 4062]

num_stops_veh = len(veh_df)

total_ons = veh_df['ons'].sum()

total_offs = veh_df['offs'].sum()

pct_with_boarding_veh = (veh_df['ons'] >= 1).sum() / num_stops_veh * 100 if num_stops_veh > 0 else 0

print("\nB.i. Number of stops by vehicle 4062:", num_stops_veh)
print("B.ii. Total passengers boarded on 4062:", total_ons)
print("B.iii. Total passengers deboarded from 4062:", total_offs)
print(f"B.iv. % of 4062's stops with at least one boarding: {pct_with_boarding_veh:.2f}%")

system_p = (stops_df['ons'] >= 1).mean()
print(f"\n System-wide proportion of stops with boardings: {system_p:.4f} ({system_p * 100:.2f}%)\n")

results = []
for vehicle_id, group in stops_df.groupby('vehicle_number'):
    total_stops = len(group)
    boarding_stops = (group['ons'] >= 1).sum()
    boarding_rate = boarding_stops / total_stops if total_stops > 0 else 0

    # Perform binomial test
    test = binomtest(k=boarding_stops, n=total_stops, p=system_p, alternative='two-sided')
    p_value = test.pvalue

    results.append({
        'vehicle_id': vehicle_id,
        'total_stops': total_stops,
        'boarding_stops': boarding_stops,
        'boarding_rate': boarding_rate,
        'p_value': p_value
    })

biased_df = pd.DataFrame(results)

print(" All Vehicles Boarding Behavior:\n")
for row in biased_df.itertuples():
    print(f"Vehicle {row.vehicle_id} — Stops: {row.total_stops}, Boardings: {row.boarding_stops}, "
          f"Rate: {row.boarding_rate:.2%}, p-value: {row.p_value:.4f}")

print("\nVehicles with Biased Boarding Data (p < 0.05):\n")
biased_vehicles = biased_df[biased_df['p_value'] < 0.05].sort_values(by='p_value')
for row in biased_vehicles.itertuples():
    print(f"Vehicle {row.vehicle_id} — Stops: {row.total_stops}, Boardings: {row.boarding_stops}, "
          f"Rate: {row.boarding_rate:.2%}, p-value: {row.p_value:.4f}")

pos_df = pd.read_csv("trimet_relpos_2022-12-07.csv")
pos_df.columns = [col.lower() for col in pos_df.columns]
relpos_values = pos_df['relpos'].values

print("Number of RELPOS entries:", len(relpos_values))
print("First 5 RELPOS values:", relpos_values[:5])

vehicle_relpos_results = []

assert 'vehicle_number' in pos_df.columns and 'relpos' in pos_df.columns

all_relpos = pos_df['relpos'].values

for vehicle_id, group in pos_df.groupby('vehicle_number'):
    vehicle_relpos = group['relpos'].values

    t_stat, p_value = ttest_ind(vehicle_relpos, all_relpos, equal_var=False)

    vehicle_relpos_results.append({
        'vehicle_id': vehicle_id,
        'num_points': len(vehicle_relpos),
        'mean_relpos': vehicle_relpos.mean(),
        't_statistic': t_stat,
        'p_value': p_value
    })

vehicle_bias_df = pd.DataFrame(vehicle_relpos_results)

vehicle_bias_df = vehicle_bias_df.sort_values(by='p_value')

print("Vehicles with Potential GPS Bias (p < 0.05):")
biased_gps_vehicles = vehicle_bias_df[vehicle_bias_df['p_value'] < 0.05]
print(biased_gps_vehicles.head())
