# -*- coding: utf-8 -*-
"""data-gathering-Bsoup-api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rjZ8jKEUQVDi26kDlfJJyYuUsMSyKKs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline  # Uncomment in Jupyter if needed
from urllib.request import urlopen
from bs4 import BeautifulSoup
import re

url = "https://www.hubertiming.com/results/2023WyEasterLong"
html = urlopen(url)
soup = BeautifulSoup(html, 'lxml')
print(type(soup))

# Get page title
title = soup.title
print("Page Title:", title.text)

# Get all links
all_links = soup.find_all("a")
for link in all_links:
    print(link.get("href"))

# Print the first 10 rows (HTML table rows)
rows = soup.find_all('tr')
print(rows[:10])

for row in rows:
    row_td = row.find_all('td')
print(row_td)
print(type(row_td))

# Convert to string and remove tags
str_cells = str(row_td)
cleantext = BeautifulSoup(str_cells, "lxml").get_text()
print(cleantext)

list_rows = []
for row in rows:
    cells = row.find_all('td')
    str_cells = str(cells)
    clean = re.compile('<.*?>')
    clean2 = (re.sub(clean, '', str_cells))
    list_rows.append(clean2)

print(clean2)
print(type(clean2))

df = pd.DataFrame(list_rows)
df1 = df[0].str.split(',', expand=True)
df1.head(10)

col_labels = soup.find_all('th')
all_header = []
col_str = str(col_labels)
cleantext2 = BeautifulSoup(col_str, "lxml").get_text()
all_header.append(cleantext2)
print(all_header)

df2 = pd.DataFrame(all_header)
df3 = df2[0].str.split(',', expand=True)
df3.head()

frames = [df3, df1]
df4 = pd.concat(frames)
df5 = df4.rename(columns=df4.iloc[0])
df5.head()

df5.info()
df6 = df5.dropna(axis=0, how='any')
df6.info()

df7 = df6.drop(df6.index[0])
df7.head()

df7.rename(columns={'[Place': 'Place'}, inplace=True)
df7.rename(columns={' Team]': 'Team'}, inplace=True)
df7['Team'] = df7['Team'].str.strip(']')
df7.head()

time_list = df7[' Gun Time'].tolist()
time_mins = []

for i in time_list:
    parts = i.strip().split(':')
    if len(parts) == 3:
        h, m, s = parts
    elif len(parts) == 2:
        h, m = parts
        s = 0
    else:
        print(f"Unexpected format: {i}")
        continue
    total_seconds = int(h) * 3600 + int(m) * 60 + int(s)
    time_mins.append(total_seconds / 60)

df7['Runner_mins'] = time_mins
df7.head()

df7.describe(include=[np.number])

from pylab import rcParams
rcParams['figure.figsize'] = 15, 5

df7.boxplot(column='Runner_mins')
plt.grid(True, axis='y')
plt.ylabel('Chip Time')
plt.xticks([1], ['Runners'])
plt.show()

x = df7['Runner_mins']
sns.histplot(x, kde=True, color='m', bins=25, edgecolor='black')
plt.show()

f_fuko = df7.loc[df7[' Gender'] == ' F']['Runner_mins']
m_fuko = df7.loc[df7[' Gender'] == ' M']['Runner_mins']

sns.histplot(f_fuko, kde=True, label='Female', edgecolor='black', color='purple')
sns.kdeplot(m_fuko, label='Male', color='blue')
plt.legend()
plt.show()

g_stats = df7.groupby(" Gender", as_index=True).describe()
print(g_stats)

df7.boxplot(column='Runner_mins', by=' Gender')
plt.ylabel('Chip Time')
plt.suptitle("")
plt.show()